Pokedex/Pokedex/Controllers/PokemonRegionController.cs
using Microsoft.AspNetCore.Mvc;
using Pokedex.core.Application.Interfaces.Services;
using Pokedex.core.Application.ViewModel;
using Pokedex.infraestruture.Persistence.Context;

namespace Pokedex.Controllers
{
    public class PokemonRegionController : Controller
    {
        private readonly IPokemonRegionServices _pokemonRegionServices;

        public PokemonRegionController(IPokemonRegionServices DbContex)
        {
            _pokemonRegionServices = DbContex;
        }


        //index
        public async Task<IActionResult> Index()
        {
            return View(await _pokemonRegionServices.GetAllPokemonsServices());
        }

        //create
        public async Task<IActionResult> CreatePokemonsRegion()
        {
            return View("SavePokemonRegion", new SavePokemonRegionViewModel());
        }

        [HttpPost]
        public async Task<IActionResult> CreatePokemonsRegion(SavePokemonRegionViewModel sptvm)
        {
            if (!ModelState.IsValid)
            {
                return View("SavePokemonRegion", sptvm);
            }

            await _pokemonRegionServices.Add(sptvm);
            return RedirectToRoute(new { controller = "PokemonRegion", action = "Index" });
        }

        //edit
        public async Task<IActionResult> EditPokemonsRegion(int id)
        {
            return View("SavePokemonRegion", await _pokemonRegionServices.GetOneByIdServices(id));
        }

        [HttpPost]
        public async Task<IActionResult> EditPokemonsRegion(SavePokemonRegionViewModel sptvm)
        {
            if (!ModelState.IsValid)
            {
                return View("SavePokemonRegion", sptvm);
            }

            await _pokemonRegionServices.Update(sptvm);
            return RedirectToRoute(new { controller = "PokemonRegion", action = "Index" });
        }

        //delete
        public async Task<IActionResult> Delete(int id)
        {
            return View(await _pokemonRegionServices.GetOneByIdServices(id));
        }

        [HttpPost]
        public async Task<IActionResult> DeletePost(int id)
        {

            await _pokemonRegionServices.Delete(id);
            return RedirectToRoute(new { controller = "PokemonRegion", action = "Index" });
        }
    }
}

Pokedex/Pokedex/Controllers/PokemonTypesController.cs
using Microsoft.AspNetCore.Mvc;
using Pokedex.core.Application.Interfaces.Services;
using Pokedex.core.Application.Services;
using Pokedex.core.Application.ViewModel;
using Pokedex.infraestruture.Persistence.Context;

namespace Pokedex.Controllers
{
    public class PokemonTypesController : Controller
    {

        private readonly IPokemonTypeServices _pokemonTypesServices;

        public PokemonTypesController(IPokemonTypeServices DbContex)
        {
            _pokemonTypesServices = DbContex;
        }

        
        //index
        public async Task<IActionResult> Index()
        {
            return View(await _pokemonTypesServices.GetAllPokemonsServices());
        }

        //create
        public async Task<IActionResult> CreatePokemonsTypes()
        {
            return View("SavePokemonTypes", new SavePokemonTypeViewModel());
        }

        [HttpPost]
        public async Task<IActionResult> CreatePokemonsTypes(SavePokemonTypeViewModel sptvm)
        {
            if (!ModelState.IsValid)
            {
                return View("SavePokemonTypes", sptvm);
            }

            await _pokemonTypesServices.Add(sptvm);
            return RedirectToRoute(new { controller = "PokemonTypes", action = "Index" });
        }

        //edit
        public async Task<IActionResult> EditPokemonsTypes(int id)
        {
            return View("SavePokemonTypes", await _pokemonTypesServices.GetOneByIdServices(id));
        }

        [HttpPost]
        public async Task<IActionResult> EditPokemonsTypes(SavePokemonTypeViewModel sptvm)
        {
            if (!ModelState.IsValid)
            {
                return View("SavePokemonTypes", sptvm);
            }

            await _pokemonTypesServices.Update(sptvm);
            return RedirectToRoute(new { controller = "PokemonTypes", action = "Index" });
        }

        //delete
        public async Task<IActionResult> Delete(int id)
        {
            return View(await _pokemonTypesServices.GetOneByIdServices(id));
        }

        [HttpPost]
        public async Task<IActionResult> DeletePost(int id)
        {

            await _pokemonTypesServices.Delete(id);
            return RedirectToRoute(new { controller = "PokemonTypes", action = "Index" });
        }
    }
}

Pokedex/Pokedex/Controllers/PokemonsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Pokedex.core.Application.Interfaces.Services;
using Pokedex.core.Application.ViewModel;
using Pokedex.infraestruture.Persistence.Context;

namespace Pokedex.Controllers
{
    public class PokemonsController : Controller
    {
        private readonly IPokemonServices _pokemonServices;

        public PokemonsController(IPokemonServices DbContex)
        {

            _pokemonServices = DbContex;

        }

        public async Task<IActionResult> Index()
        {
            return View(await _pokemonServices.GetAllPokemonsServices());
        }

        //create
        public async Task<IActionResult> CreatePokemons()
        {

            return View("SavePokemons", new SavePokemonsViewModel());
        }

        [HttpPost]
        public async Task<IActionResult> CreatePokemons(SavePokemonsViewModel spvm)
        {
            if (!ModelState.IsValid) 
            {
                return View("SavePokemons", spvm);
            }

            await _pokemonServices.Add(spvm);
            return RedirectToRoute(new { controller="Pokemons", action="Index" });
        }

        //edit
        public async Task<IActionResult> EditPokemons(int id)
        {
            return View("SavePokemons", await _pokemonServices.GetOneByIdServices(id));
        }

        [HttpPost]
        public async Task<IActionResult> EditPokemons(SavePokemonsViewModel spvm)
        {
            if (!ModelState.IsValid)
            {
                return View("SavePokemons", spvm);
            }

            await _pokemonServices.Update(spvm);
            return RedirectToRoute(new { controller = "Pokemons", action = "Index" });
        }

        //delect
        public async Task<IActionResult> Delete(int id)
        {
            return View(await _pokemonServices.GetOneByIdServices(id));
        }

        [HttpPost]
        public async Task<IActionResult> DeletePost(int id)
        {
            
            await _pokemonServices.Delete(id);
            return RedirectToRoute(new { controller = "Pokemons", action = "Index" });
        }

    }
}

Pokedex/Pokedex/Controllers/pokedexController.cs
using Microsoft.AspNetCore.Mvc;
using Pokedex.core.Application.Interfaces.Services;
using Pokedex.infraestruture.Persistence.Context;

namespace Pokedex.Controllers
{
    public class pokedexController : Controller
    {

        private readonly IPokemonServices _pokemonServices;
        private readonly IPokemonRegionServices _pokemonR;
        private readonly IPokemonTypeServices _pokemonT;


        public pokedexController(IPokemonRegionServices DbContex, IPokemonTypeServices DbContexT, IPokemonServices DbContextP ) 
        {

            _pokemonServices = DbContextP;
            _pokemonR = DbContex;
            _pokemonT = DbContexT;

        }

        public async Task<IActionResult>Index()
        {
            await _pokemonR.GetAllPokemonsServices();
            await _pokemonT.GetAllPokemonsServices();

            return View(await _pokemonServices.GetAllPokemonsServices());
        }
    }
}

Pokedex/Pokedex/Views/PokemonRegion/Delete.cshtml
@model Pokedex.core.Application.ViewModel.SavePokemonRegionViewModel



<div class="row">

    <div class="col-12">
        <div class="card bg-dark text-white border border-5 rounded-3 shadow">
            <div class="card-header">
                <h4 class="text-center">Do you like to delete this Pokemon Region?</h4>
            </div>
            <form method="post" asp-controller="PokemonRegion" asp-action="DeletePost">
                <div class="card-body">
                    <div class="row d-flex">
                        <div class="col-12 col-md-6">
                            <ul>
                                <li>Name: @Model.pokemonRegionsName</li>
                            </ul>
                        </div>
                    </div>
                    <input type="hidden" asp-for="id" />
                </div>
                <div class="card-footer">
                    <button class="btn btn-outline-danger">Delete</button>
                    <a class="btn btn-outline-info" asp-controller="PokemonRegion" asp-action="Index">Go back</a>
                </div>
            </form>
        </div>
    </div>

</div>

Pokedex/Pokedex/Views/PokemonRegion/Index.cshtml
@model IEnumerable<Pokedex.core.Application.ViewModel.PokemonRegionViewModel>

<div class="row">
    <div class="col-12">
        <div class="d-flex justify-content-end mb-4">
            <a class="btn btn-outline-success" asp-controller="PokemonRegion" asp-action="CreatePokemonsRegion">Create</a>
        </div>
    </div>
    <div class="card text-white bg-dark">
        <div class="card-body">
            <table class="table table-dark table-striped table-responsive">
                <thead>
                    <tr class="text-center">
                        <th scope="col">#</th>
                        <th scope="col">Region of Pokemon</th>
                        <th scope="col">Opcions</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (Pokedex.core.Application.ViewModel.PokemonRegionViewModel item in Model)
                    {
                        <tr class="text-center">
                            <th scope="row">@item.id</th>
                            <td>@item.pokemonRegionsName</td>
                            <td class="d-flex justify-content-center">
                                <a class="btn btn-outline-warning me-2" asp-controller="PokemonRegion" asp-action="EditPokemonsRegion" asp-route-id="@item.id">edit</a>
                                <a class="btn btn-outline-danger" asp-controller="PokemonRegion" asp-action="Delete" asp-route-id="@item.id">delete</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

Pokedex/Pokedex/Views/PokemonRegion/SavePokemonRegion.cshtml
@model Pokedex.core.Application.ViewModel.SavePokemonRegionViewModel;
@{
    ViewData["Title"] = "Save Pokemons Regions";
}


<div class="col-6 offset-3">
    <div class="card bg-black text-white">
        <form method="post" class="saveTypeForm">
            <div class="card-body">

                <input type="hidden" asp-for="id" class="IDSave" />

                <div class="mb-3">
                    <label class="form-label" asp-for="pokemonRegionsName">Pokemon Region:</label>
                    <input class="form-control" asp-for="pokemonRegionsName" type="text" />
                    <span asp-validation-for="pokemonRegionsName" class="text-danger"></span>
                </div>

            </div>
            <div class="card-footer">
                <button class="btn btn-outline-success">Save</button>
                <a class="btn btn-outline-info" asp-controller="PokemonRegion" asp-action="Index">Go back</a>
            </div>
        </form>
    </div>
</div>

Pokedex/Pokedex/Views/PokemonTypes/Delete.cshtml
@model Pokedex.core.Application.ViewModel.SavePokemonTypeViewModel



<div class="row">

    <div class="col-12">
        <div class="card bg-dark text-white border border-5 rounded-3 shadow">
            <div class="card-header">
                <h4 class="text-center">Do you like to delete this Pokemon?</h4>
            </div>
            <form method="post" asp-controller="PokemonTypes" asp-action="DeletePost">
                <div class="card-body">
                    <div class="row d-flex">
                        <div class="col-12 col-md-6">
                            <ul>
                                <li>Name: @Model.typeName</li>
                            </ul>
                        </div>
                    </div>
                    <input type="hidden" asp-for="id" />
                </div>
                <div class="card-footer">
                    <button class="btn btn-outline-danger">Delete</button>
                    <a class="btn btn-outline-info" asp-controller="PokemonTypes" asp-action="Index">Go back</a>
                </div>
            </form>
        </div>
    </div>

</div>

Pokedex/Pokedex/Views/PokemonTypes/Index.cshtml
@model IEnumerable<Pokedex.core.Application.ViewModel.PokemonTypesViewModel>

<div class="row">
    <div class="col-12">
        <div class="d-flex justify-content-end mb-4">
            <a class="btn btn-outline-success" asp-controller="PokemonTypes" asp-action="CreatePokemonsTypes">Create</a>
        </div>
    </div>
        <div class="card text-white bg-dark">
            <div class="card-body">
                <table class="table table-dark table-striped table-responsive">
                    <thead>
                        <tr class="text-center">
                            <th scope="col">#</th>
                            <th scope="col">Type of Pokemon</th>
                            <th scope="col">Opcions</th>
                        </tr>
                    </thead>
                    <tbody>
                    @foreach (Pokedex.core.Application.ViewModel.PokemonTypesViewModel item in Model)
                    {
                        <tr class="text-center">
                            <th scope="row">@item.id</th>
                            <td>@item.typeName</td>
                            <td class="d-flex justify-content-center">
                                <a class="btn btn-outline-warning me-2" asp-controller="PokemonTypes" asp-action="EditPokemonsTypes" asp-route-id="@item.id">edit</a>
                                <a class="btn btn-outline-danger" asp-controller="PokemonTypes" asp-action="Delete" asp-route-id="@item.id">delete</a>
                            </td>
                        </tr>
                    }
                    </tbody>
                </table>
            </div>
        </div>
</div>

Pokedex/Pokedex/Views/PokemonTypes/SavePokemonTypes.cshtml
@model Pokedex.core.Application.ViewModel.SavePokemonTypeViewModel;
@{
    ViewData["Title"] = "Save Pokemons Types";
}


<div class="col-6 offset-3">
    <div class="card bg-black text-white">
        <form method="post" class="saveTypeForm">
            <div class="card-body">

                <input type="hidden" asp-for="id" class="IDSave" />

                <div class="mb-3">
                    <label class="form-label" asp-for="typeName">Pokemon Name:</label>
                    <input class="form-control" asp-for="typeName" type="text" />
                    <span asp-validation-for="typeName" class="text-danger"></span>
                </div>
                
            </div>
            <div class="card-footer">
                <button class="btn btn-outline-success">Save</button>
                <a class="btn btn-outline-info" asp-controller="PokemonTypes" asp-action="Index">Go back</a>
            </div>
        </form>
    </div>
</div>

Pokedex/Pokedex/Views/Pokemons/Index.cshtml
@model IEnumerable<Pokedex.core.Application.ViewModel.PokemonsViewModels>;
@{
    ViewData["Title"] = "Pokemons";

    var typePokemonNamen = ViewBag.PokemonsT;
    var count = ViewBag.CountT;
}

<div class="row">
    <div class="col-12">
        <div class="d-flex justify-content-end mb-4">
            <a class="btn btn-outline-success" asp-controller="Pokemons" asp-action="CreatePokemons">Create</a>
        </div>
    </div>
    <div class="card text-white bg-dark">
        <div class="card-body">
            <table class="table table-dark table-striped table-responsive">
                <thead>
                    <tr class="text-center">
                        <th scope="col">#</th>
                        <th scope="col">Pokemon Name</th>
                        <th scope="col">Pokemon Img</th>
                        <th scope="col">Type 1 of pokemon</th>
                        <th scope="col">Type 2 of pokemon</th>
                        <th scope="col">Opcions</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (Applications.ViewModel.PokemonsViewModels item in Model)
                    {
                        <tr class="text-center">
                            <th scope="row">@item.id</th>
                            <td>
                                <img src="@item.pokemonImg" class="img-size" alt="@item.pokemonName">
                            </td>
                            <td>@item.pokemonName</td>
                            <td>@item.typesPrimaryPokemons.typeName</td>
                            <td>
                                @for (var i = 0; i < count; i++)
                                {
                                    @if (item.TypeSecondaryPokemonId == typePokemonNamen[i].id ) 
                                    {
                                        @typePokemonNamen[i].typeName
                                    }
                                }
                            </td>
                            <td class="">
                                <a class="btn btn-outline-warning col-12  mb-4" asp-controller="Pokemons" asp-action="EditPokemons" asp-route-id="@item.id">edit</a>
                                <a class="btn btn-outline-danger col-12 " asp-controller="Pokemons" asp-action="Delete" asp-route-id="@item.id">delete</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

Pokedex/Pokedex/Views/Pokemons/SavePokemons.cshtml
@model Pokedex.core.Application.ViewModel.SavePokemonsViewModel
@{
    ViewData["Title"] = "Save Pokemons";
    var listPT = ViewBag.PokemonsT;
    var ListPR = ViewBag.PokemonsR;
    var countTP = ViewBag.CountT;
    var countRP = ViewBag.CountR;
}

<div class="row">

    <div class="col-6 offset-3">
        <div class="card bg-black text-white">
            <form method="post" class="saveForm">
                <div class="card-body">

                    <input type="hidden" asp-for="id" class="IDSave"/>

                    <div class="mb-3">
                        <label class="form-label" asp-for="pokemonName">Pokemon Name:</label>
                        <input class="form-control" asp-for="pokemonName" type="text" />
                        <span asp-validation-for="pokemonName" class="text-danger"></span>
                    </div>

                    <div class="mb-3">
                        <label class="form-label" asp-for="pokemonImg">Pokemon url Img:</label>
                        <input class="form-control" asp-for="pokemonImg" type="text" />
                        <span asp-validation-for="pokemonImg" class="text-danger"></span>
                    </div>

                    <div class="mb-3">
                        <label class="form-label" asp-for="pokemonRegionId">Pokemon Regions:</label>
                        <select class="form-select" asp-for="pokemonRegionId">
                            <option selected>---Regions---</option>
                            @for (var i = 0; i < @countRP; i++)
                            {
                                <option value="@ListPR[i].id">@ListPR[i].pokemonRegionsName</option>
                            }
                        </select>
                        <span asp-validation-for="pokemonRegionId" class="text-danger"></span>
                    </div>

                    <div class="mb-3">
                        <label class="form-label" asp-for="TypePrimaryPokemonId">Pokemon Type1:</label>
                        <select class="form-select" asp-for="TypePrimaryPokemonId">
                            <option selected>---Type1---</option>
                            @for (var i = 0; i < @countTP; i++)
                            {
                                <option value="@listPT[i].id">@listPT[i].typeName</option>
                            }
                        </select>
                        <span asp-validation-for="TypePrimaryPokemonId" class="text-danger"></span>
                    </div>

                    <div class="mb-3">
                        <label class="form-label" asp-for="TypeSecondaryPokemonId">Pokemon Type2:</label>
                        <select class="form-select"  asp-for="TypeSecondaryPokemonId">
                            <option selected>---type2</option>
                            @for (var i = 0; i < @countTP; i++)
                            {
                                <option value="@listPT[i].id">@listPT[i].typeName</option>
                            }
                        </select>
                        <span asp-validation-for="TypeSecondaryPokemonId" class="text-danger"></span>
                    </div>

                </div>
                <div class="card-footer">
                    <button class="btn btn-outline-success">Save</button>
                    <a class="btn btn-outline-info" asp-controller="Pokemons" asp-action="Index">Go back</a>
                </div>
            </form>
        </div>
    </div>

</div>

Pokedex/Pokedex/Views/Pokemons/delete.cshtml
@model Pokedex.core.Application.ViewModel.SavePokemonsViewModel


<div class="row">

    <div class="col-12">
        <div class="card bg-dark text-white border border-5 rounded-3 shadow">
            <div class="card-header">
                <h4 class="text-center">Do you like to delete this Pokemon?</h4>
            </div>
            <form method="post" asp-controller="Pokemons" asp-action="DeletePost">
                <div class="card-body">
                    <div class="row d-flex ">
                        <div class="col-12 col-md-6">
                            <img class="img-thumbnail" src="@Model.pokemonImg" alt="@Model.pokemonName" />
                        </div>
                        <div class="col-12 col-md-6">
                           <ul>
                               <li>Name: @Model.pokemonName</li>
                               <li>Region: @Model.pokemonRegionId</li>
                               <li>Type primary: @Model.TypePrimaryPokemonId</li>
                               <li>Type secondary: @Model.TypeSecondaryPokemonId</li>
                           </ul>
                        </div>
                    </div>
                    <input type="hidden" asp-for="id" />
                </div>
                <div class="card-footer">
                    <button class="btn btn-outline-danger">Delete</button>
                    <a class="btn btn-outline-info" asp-controller="Pokemons" asp-action="Index">Go back</a>
                </div>
            </form>
        </div>
    </div>

</div>

Pokedex/Pokedex/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Pokedex</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Pokedex.styles.css" asp-append-version="true" />
</head>
<body class="bg-dark text-white">
    
    <header class="mb-5">
        <nav class="navbar navbar-dark navbar-expand-lg">
          <div class="container-fluid">
            <a class="navbar-brand" asp-controller="pokedex" asp-action="Index">Pokedex</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarScroll">
              <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
                <li class="nav-item">
                  <a class="nav-link active" asp-controller="pokedex" asp-action="Index">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" asp-controller="Pokemons" asp-action="Index">Pokemons</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" asp-controller="PokemonRegion" asp-action="Index">Pokemons Regions</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" asp-controller="PokemonTypes" asp-action="Index">Pokemons Type</a>
                </li>
              </ul>
              <form class="d-flex" role="search">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Search</button>
              </form>
            </div>
          </div>
        </nav>
    </header>

    <div class="container mt-3">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Pokedex/Pokedex/Views/pokedex/Index.cshtml
@model List<Pokedex.core.Application.ViewModel.PokemonsViewModels>


<div class="row">
    @foreach (Pokedex.core.Application.ViewModel.PokemonsViewModels item in Model)
    {
        <div class="card me-3 mb-4 bg-dark text-white col-12 col-md-4 border border-5 border-info shadow">
            <div class="card-body">
                <div class="mb-3 col-12 border-bottom border-3 text-center">
                    <img src="@item.pokemonImg" class="img-size" alt="@item.pokemonName">
                </div>
                <div>
                    <ul>
                        <li>Name: @item.pokemonName</li>
                        <li>Region: @item.pokemonRegions.pokemonRegionsName</li>
                        <li>Type: @item.typesPrimaryPokemons.typeName</li>
                    </ul>
                </div>
            </div>
        </div>
    }

</div>